project:
  type: website
  output-dir: docs

website:
  title: "temp_website"
  favicon: fav-icon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: fyp-project.qmd
        text: FYP Project
      - href: data-viz.qmd
        text: Data Visualization
      - href: reflection.qmd
        text: Reflection on the use of GenAI

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



